### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by clbarnes** [asomers/blosc-rs#27]
By linking a C library, it's obviously harder to get blosc-rs to run in a browser. However, c-blosc itself can be compiled to WASM (see https://github.com/Blosc/c-blosc/issues/238#issuecomment-513735307 and https://github.com/manzt/numcodecs.js/tree/main/codecs/blosc ). I don't know much about linking C libraries or WASM itself (other than running `cargo build` and praying...); is it possible to bake that kind of configuration into a `build.rs` and gain WASM support for blosc-sys? I gather the hard bit is the FFI between rust and C.

I suppose there could alternatively be a separate crate which generates a WASM blob as above and then writes a dependent rust wrapper around it with js_sys for API niceness.

**Comment by kylebarron** [comment]
Most rust-wasm packages use the `wasm32-unknown-unknown` target instead of the `wasm32-unknown-emscripten` target, which is what you'd need to use if you have a C library. The tooling around the rust+emscripten bindings isn't very good https://github.com/rustwasm/team/issues/291

**Comment by asomers** [comment]
I'm going to close this issue because nobody seems to be working on it.  And to be clear, I'm not going to do it myself; I know nothing about wasm or browsers.  But I can help you with the blosc side if you try it.
