### ISSUE TITLE
Linker errors

### ISSUE THREAD

**Issue by mwlon** [asomers/blosc-rs#28]
When trying to build a small project with `blosc` as a dependency, I get this linker error:

``` 
= note: ld: library 'blosc' not found
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

blosc version: 0.2.0
OS: Mac
Processor: Apple Silicon
Rust version: 1.73.0

**Comment by asomers** [comment]
Do you actually have c-blosc2 installed?  If so, what is the path to libblosc2.so ?  And what is the actual linker output?

**Comment by mwlon** [comment]
I don't have it installed. Generally Rust libraries build what they need from source, but do you expect the library to be on the system path? If so, I think everyone would find it helpful if you put installation instructions at the top of your README.

**Comment by asomers** [comment]
That's right.  This crate merely contains bindings for c-blosc; it doesn't distribute c-blosc itself.  See #11 and #17 for discussion of why it doesn't include the actual library.
