### ISSUE TITLE
segfaults on Ubuntu 18.04

### ISSUE THREAD

**Issue by mulimoen** [asomers/blosc-rs#8]
This is due to unconditional setting of the two last parameters of `blosc_get_complib_info` and `blosc_get_complib_info` not accepting a string which it does not recognize.

This is fixed upstream, but older libraries are still in use by some distros
https://github.com/Blosc/c-blosc/issues/227
https://github.com/Blosc/c-blosc/issues/228

**Comment by asomers** [comment]
Yeah, I filed those bugs :) .  The intent of blosc-sys is that it requires the minimum c-blosc version as its current version.  That's 1.14.4 right now.  I would rather modify the build script to simply fail with older c-blosc versions rather than add workarounds.

**Comment by mulimoen** [comment]
Shame they didn't backport the fix to ubuntu!

**Comment by mulimoen** [comment]
Would it be an idea to bundle the source behind a feature gate?

**Comment by asomers** [comment]
You mean like vendoring the source of c-blosc?  Would you have Cargo build and install the library then?

**Comment by mulimoen** [comment]
Yes, and the `cmake` crate is perfect for this. You don't need to install the library system wide as it will be statically linked. I would be happy to provide such a feature if you'd like.

**Comment by asomers** [comment]
Closing as discussed in PR #11
